import './TPS.js'
import './Forms/ActionForm.js'
import './Forms/MessageForm.js'
import './Forms/ModalForm.js'
import './Leaderboards.js'
import './PearlCooldown.js'
import './Hit.js'
import './BowDing.js'